"""empty message

Revision ID: 029640b961f0
Revises: d1dc0b75eec4
Create Date: 2020-04-17 01:15:18.316878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029640b961f0'
down_revision = 'd1dc0b75eec4'
branch_labels = None
depends_on = None


def upgrade():
  op.create_unique_constraint('dictionaries_words_unique_constraint', 'user_words', ['word_id', 'dictionary_id'])
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
  op.drop_constraint('dictionaries_words_unique_constraint', 'user_words')

    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
