"""add refresh token to users

Revision ID: 72f6f51d2a9e
Revises: 04acbaad1af2
Create Date: 2020-05-01 15:44:13.458549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72f6f51d2a9e'
down_revision = '04acbaad1af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('access_token_expiration', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_access_token'), 'users', ['access_token'], unique=True)
    op.create_index(op.f('ix_users_refresh_token'), 'users', ['refresh_token'], unique=True)
    op.drop_index('ix_users_token', table_name='users')
    op.drop_column('users', 'token')
    op.drop_column('users', 'token_expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index('ix_users_token', 'users', ['token'], unique=True)
    op.drop_index(op.f('ix_users_refresh_token'), table_name='users')
    op.drop_index(op.f('ix_users_access_token'), table_name='users')
    op.drop_column('users', 'refresh_token_expiration')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token_expiration')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
