"""remove sentences

Revision ID: eee8dd22498b
Revises: 35ae5ae49c42
Create Date: 2020-05-17 16:43:43.700445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee8dd22498b'
down_revision = '35ae5ae49c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentences')
    op.add_column('translations', sa.Column('sentence', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'sentence')
    op.create_table('sentences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('translation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], name='sentences_translation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sentences_pkey')
    )
    # ### end Alembic commands ###
