"""adds timestamps to users

Revision ID: e1741290b6a9
Revises: 141d0e8b40d0
Create Date: 2020-04-10 13:32:53.331504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1741290b6a9'
down_revision = '141d0e8b40d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_modified')
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
