"""adds composite fk on user words


Revision ID: 892865eb349e
Revises: 029640b961f0
Create Date: 2020-04-17 11:13:49.318173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892865eb349e'
down_revision = '029640b961f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_dictionary_word_combo_id', 'user_words', ['word_id', 'dictionary_id'])
    op.create_index(op.f('ix_user_words_dictionary_id'), 'user_words', ['dictionary_id'], unique=False)
    op.create_index(op.f('ix_user_words_word_id'), 'user_words', ['word_id'], unique=False)
    op.drop_constraint('dictionaries_words_unique_constraint', 'user_words', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('dictionaries_words_unique_constraint', 'user_words', ['word_id', 'dictionary_id'])
    op.drop_index(op.f('ix_user_words_word_id'), table_name='user_words')
    op.drop_index(op.f('ix_user_words_dictionary_id'), table_name='user_words')
    op.drop_constraint('_dictionary_word_combo_id', 'user_words', type_='unique')
    # ### end Alembic commands ###
