"""composite foreign key for translations

Revision ID: 8b2adfd37486
Revises: b0e72eb8422c
Create Date: 2020-05-17 17:18:46.246190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2adfd37486'
down_revision = 'b0e72eb8422c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('dictionary_id', sa.Integer(), nullable=True))
    op.add_column('translations', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'translations', 'user_words', ['word_id', 'dictionary_id'], ['word_id', 'dictionary_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.drop_column('translations', 'word_id')
    op.drop_column('translations', 'dictionary_id')
    # ### end Alembic commands ###
