"""adds created by to word

Revision ID: 66897cbc00a9
Revises: 8b2adfd37486
Create Date: 2020-05-17 19:09:33.387195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66897cbc00a9'
down_revision = '8b2adfd37486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('created_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'created_by')
    # ### end Alembic commands ###
