"""adds indexes to timestamps

Revision ID: fa6f3c3bf9f0
Revises: 28829b02f963
Create Date: 2020-04-10 14:45:00.262147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6f3c3bf9f0'
down_revision = '28829b02f963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dictionary_date_created'), 'dictionary', ['date_created'], unique=False)
    op.create_index(op.f('ix_user_date_created'), 'user', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_date_created'), table_name='user')
    op.drop_index(op.f('ix_dictionary_date_created'), table_name='dictionary')
    # ### end Alembic commands ###
