"""adds timestamps to users

Revision ID: ecefebb0e35f
Revises: b9903a5f902c
Create Date: 2020-04-10 14:41:19.295657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecefebb0e35f'
down_revision = 'b9903a5f902c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_modified')
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
